### PR TITLE
Patrick/detectron2 without negative class assertions

### PR DESCRIPTION
**Pull request by patrickwilliams3**
Some new changes from detectron2 master branch as well as my changes which include
1. Changing cfg.TWA.DIRECTORY.TRAIN/VAL/TEST to lists
2. Removing assertions that prevent negative class ids (which we use since __background__ has id of -1)
3. Add prefetch_factor back to paramater of function so that its decorator can legally pass it in

---
This change is [Reviewable](https://reviewable.io/reviews/thirdwave-ai/detectron2/13)

### CODE REVIEW

**Review by danielgordon10 — APPROVED** [review]
:lgtm_strong: 

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/detectron2/13#-:-Mef151y6dtdRX1513QF:b-uwkowd)* status: all files reviewed, 3 unresolved discussions (waiting on @patrickwilliams3)

___
*[detectron2/data/build.py, line 172 at r1](https://reviewable.io/reviews/thirdwave-ai/detectron2/13#-Mef0dfi5f7W0ANDxS3c:-Mef0cVW3UHppM_da_Ey:bkf0tsx) ([raw file](https://github.com/thirdwave-ai/detectron2/blob/24a3fe01824a18664b82f929eca970d4ff5350ba/detectron2/data/build.py#L172)):*
> ```
>         if len(classes):
>             assert classes.min() >= 0, f"Got an invalid category_id={classes.min()}"
> ```
Instead of removing, what about changing it to a `warnings.warn`?
___
*[detectron2/data/build.py, line 173 at r1](https://reviewable.io/reviews/thirdwave-ai/detectron2/13#-Mef0jS58l4nmzAqGLvY:-Mef0jS58l4nmzAqGLvZ:b4syjis) ([raw file](https://github.com/thirdwave-ai/detectron2/blob/24a3fe01824a18664b82f929eca970d4ff5350ba/detectron2/data/build.py#L173)):*
> ```Python
>         if len(classes):
>             assert classes.min() >= 0, f"Got an invalid category_id={classes.min()}"
>             assert (
> ```

Does this one also break for us? If not, I say we keep it.
___
*[detectron2/export/c10.py, line 302 at r1](https://reviewable.io/reviews/thirdwave-ai/detectron2/13#-Mef0v804H8gnuxl1Xfn:-Mef0v804H8gnuxl1Xfo:b-dmdzou) ([raw file](https://github.com/thirdwave-ai/detectron2/blob/7c3f22f46f281b4e4b2fb3f1b0790c52abe08e99/detectron2/export/c10.py#L302)):*
> ```Python
>                 aligned = self.level_poolers[0].aligned
> 
>             x0 = x[0]
> ```

is this change from you or from them?

**Review by patrickwilliams3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/detectron2/13)* status: all files reviewed, 3 unresolved discussions (waiting on @danielgordon10 and @patrickwilliams3)

___
*[detectron2/data/build.py, line 173 at r1](https://reviewable.io/reviews/thirdwave-ai/detectron2/13#-Mef0jS58l4nmzAqGLvY:-Mf4FgIi3_M7ddEFCjxq:bef7pi6) ([raw file](https://github.com/thirdwave-ai/detectron2/blob/24a3fe01824a18664b82f929eca970d4ff5350ba/detectron2/data/build.py#L173)):*
<details><summary><i>Previously, danielgordon10 wrote…</i></summary><blockquote>

Does this one also break for us? If not, I say we keep it.
</blockquote></details>

I'd assume not, but it may be better for us to make it num_classes -1 since our classes start from id = -1 instead of id = 0. Thoughts?
___
*[detectron2/export/c10.py, line 302 at r1](https://reviewable.io/reviews/thirdwave-ai/detectron2/13#-Mef0v804H8gnuxl1Xfn:-Mf4FwlZ5MDWUV-U0wxL:b700j9w) ([raw file](https://github.com/thirdwave-ai/detectron2/blob/7c3f22f46f281b4e4b2fb3f1b0790c52abe08e99/detectron2/export/c10.py#L302)):*
<details><summary><i>Previously, danielgordon10 wrote…</i></summary><blockquote>

is this change from you or from them?
</blockquote></details>

This is a change from them.

**Comment by danielgordon10** [comment]
I think this PR is basically ready to merge (after my one comment). You can ignore the red shown on reviewable, that's mad about some detectron CI things that we don't care about.

**Review by danielgordon10 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/detectron2/13)* status: all files reviewed, 2 unresolved discussions (waiting on @patrickwilliams3)

___
*[detectron2/data/build.py, line 173 at r1](https://reviewable.io/reviews/thirdwave-ai/detectron2/13#-Mef0jS58l4nmzAqGLvY:-Mf91Jjb7hL52D75IwNQ:beiucmp) ([raw file](https://github.com/thirdwave-ai/detectron2/blob/24a3fe01824a18664b82f929eca970d4ff5350ba/detectron2/data/build.py#L173)):*
<details><summary><i>Previously, patrickwilliams3 wrote…</i></summary><blockquote>

I'd assume not, but it may be better for us to make it num_classes -1 since our classes start from id = -1 instead of id = 0. Thoughts?
</blockquote></details>

I don't think that's correct. Num classes for them doesn't include background whereas ours does I think. So we actually have one more class. I think your change will actually fail now because it will add one to class.max() which should == num_classes. I think we want it exactly as it was before.

**Review by patrickwilliams3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/thirdwave-ai/detectron2/13)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @danielgordon10 and @patrickwilliams3)

___
*[detectron2/data/build.py, line 173 at r1](https://reviewable.io/reviews/thirdwave-ai/detectron2/13#-Mef0jS58l4nmzAqGLvY:-Mf92j9K7Fgf6JfwsHkC:b-uwksoe) ([raw file](https://github.com/thirdwave-ai/detectron2/blob/24a3fe01824a18664b82f929eca970d4ff5350ba/detectron2/data/build.py#L173)):*
<details><summary><i>Previously, danielgordon10 wrote…</i></summary><blockquote>

I don't think that's correct. Num classes for them doesn't include background whereas ours does I think. So we actually have one more class. I think your change will actually fail now because it will add one to class.max() which should == num_classes. I think we want it exactly as it was before.
</blockquote></details>

You're right num_classes is defined from len(class_names) where class_names comes from MetadataCatalog which doesn't include __background__.  Removed the subtraction.

**Pull request merged**
